# Generated by Django 6.0 on 2026-01-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobio', '0019_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
