# Generated by Django 6.0 on 2026-01-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobio', '0022_userprofile_created_at_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
